# Generated by Django 5.0.2 on 2024-02-19 11:03

import crm1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('contect', models.CharField(max_length=12)),
                ('course', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('year_sem', models.CharField(max_length=50)),
                ('cgpa', models.CharField(max_length=20)),
                ('result', models.ImageField(blank=True, null=True, upload_to=crm1.models.name_date)),
            ],
        ),
    ]
